server:
    port: 10000

system:
    appId: securityapp
    token: bWlubGlhCg==
    
spring:
    profile: dev
    application:
        name: sample-petstore

    datasource:
        testOnBorrow: true
        validationQuery: "SELECT 1"
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_sample_petstore_dev_v1?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        username: root
        password:

    jpa:
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
        database: MYSQL
        show_sql: false
        properties:
          jadira.usertype.autoRegisterUserTypes: true
        hibernate:
#            naming:
#                strategy:
            ddl-auto: update

#security.jwt:
##  tokenExpirationTime: 15 # Number of minutes
#  tokenExpirationTime: 10080 # Number of minutes
#  refreshTokenExpTime: 10080 # Minutes
#  tokenIssuer: http://minlia.com
#  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
#
##spring.datasource:
##  url: "jdbc:h2:mem:testdb"
##  driverClassName: org.h2.Driver
##  username: sa
##  password: ""
##  data: "classpath*:data.sql"
##spring.jpa:
##  database-platform: org.hibernate.dialect.H2Dialect
##spring.h2.console.enabled: true
#swagger:
#    title: 安全接口
#    description: 安全接口
#    version: 2.0
#    contact: cloud@minlia.com
#    path: /api/.*
#    redirect: true
#
#aliyun:
#    oss:
#        key: LTAIkdMFkDplTUJX
##        accessId: LTAIkdMFkDplTUJX
##        accessKey: VApB4W2D6rqxJVO0WakbB1Zryn3tOQ
##        bucketName: yinxingnetwork
##        endpoint: oss-cn-shenzhen.aliyuncs.com
#        secret: VApB4W2D6rqxJVO0WakbB1Zryn3tOQ
#        bucket: yinxingnetwork
#        endpoint: oss-cn-shenzhen.aliyuncs.com
#
#    sms:
#        accessId: LTAIc3r9adaIXwpH
#        accessKey: i86XebUFjiDY7cDQVCFFpPQBOUTcZt
#        endpoint: cn-hangzhou
#        regionId: cn-hangzhou
#        product: Sms
#        domain: sms.aliyuncs.com
#        signName: 测试
#
#sms:
#    templates:
#        userRegistration: SMS_56155265
#        resetPassword: SMS_56155265
#        changePassword: SMS_56155265
#        bindOrRegistration: SMS_56155265
